DROP TABLE IF EXISTS listing;

CREATE TABLE listing (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  make VARCHAR(250) NOT NULL,
  price DOUBLE NOT NULL,
  mileage INT NOT NULL,
  seller_type VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS contact;

CREATE TABLE contact (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  listing_id INT NOT NULL,
  contact_date TIMESTAMP NOT NULL,
  CONSTRAINT FK_CONTACT_LISTING_ID FOREIGN KEY (listing_id) REFERENCES listing(id)
);